x = int(input())
y = int(input())
z = float(input())
t = float(input())

print(x - y)
print(x + z)
print(z + t)
print(x * z)
print(x / 2)
print(x / (y + 1))
print(((x + y) * z) / (4 * x))
print(1 / (x ** 0.5))